### ISSUE TITLE
Some details about "spurious wakeups"

### ISSUE THREAD

**Issue by rudro** [uber/swift-concurrency#10]
This probably should be a wiki page or something other than an issues, but just wanted to cover some details I discovered after reviewing and merging : https://github.com/uber/swift-concurrency/commit/1880d77e4afeeb9baec86539c5ce9e1ae1bd061f

The reason for having a loop is due to "spurious wakeup"s.  While it appeared to be almost a bug in the `NSCondition` API, it seems that this, while somewhat counterintuitive, is by design.

1. We don't have the source to `NSCondition`, but it seems that it's probably just a slim wrapper around `pthread_cond_wait` and `pthread_cond_timedwait`
2. This issue exists at the pthread layer, so it's not really `NSCondition`s fault
3. Spurious wakeups are mentioned clearly in the man pages : http://pubs.opengroup.org/onlinepubs/7908799/xsh/pthread_cond_wait.html
4. While it seems to be a strange API choice, it seems that someone balanced performance with was-of-use of the API and consciously chose better performance over a simpler API. Wiki page about it : https://en.wikipedia.org/wiki/Spurious_wakeup
5. Quote from that page (and elsewhere) : 

> This means that when you wait on a condition variable, the wait may (occasionally) return when no thread specifically broadcast or signaled that condition variable. Spurious wakeups may sound strange, but on some multiprocessor systems, making condition wakeup completely predictable might substantially slow all condition variable operations. The race conditions that cause spurious wakeups should be considered rare.

**Comment by neakor** [comment]
Moved this to wiki https://github.com/uber/swift-concurrency/wiki/CountDownLatch-and-Spurious-Wakeups

**Comment by davidthorn** [comment]
Really helpful, thanks for posting
