### ISSUE TITLE
`OSAtomicCompareAndSwap64Barrier`, `OSAtomicIncrement64Barrier`, `OSAtomicDecrement64Barrier` are deprecated

### ISSUE THREAD

**Issue by dworak** [uber/swift-concurrency#17]
<img width="1251" alt="screen shot 2018-10-05 at 10 14 28" src="https://user-images.githubusercontent.com/3908338/46523901-755d7780-c887-11e8-8c8f-d8ea22ac6800.png">

**Comment by dworak** [comment]
Set the deployment target to iOS 10.0

**Comment by neakor** [comment]
@dworak here's the PR (https://github.com/uber/swift-concurrency/pull/26) that addresses the deprecated APIs in `AtomicInt`. I'll follow up with another one for `AtomicReference`.
