### ISSUE TITLE
Failed to build using Carthage since 0.6.5

### ISSUE THREAD

**Issue by uroskrkic** [uber/swift-concurrency#35]
Hello,
First, thank you for this library. It is very useful.

But, I have build problem (errors) since version 0.6.5, using Carthage. The latest version which works to me is 0.6.4, but unfortunately I cannot update to any version after, including latest 0.7.1, because of build problem using Carthage.

I see some very strange hardcoded paths in build logs:
**/Users/yiw/Uber/GitHub/swift-concurrency**

Please check and thanks a lot!

Here are the logs attached for 0.6.5, 0.7.0 and 0.7.1. As said, 0.6.4 builds correctly.
[0.6.4.log](https://github.com/uber/swift-concurrency/files/3097414/0.6.4.log)
[0.6.5.log](https://github.com/uber/swift-concurrency/files/3097415/0.6.5.log)
[0.7.0.log](https://github.com/uber/swift-concurrency/files/3097416/0.7.0.log)
[0.7.1.log](https://github.com/uber/swift-concurrency/files/3097417/0.7.1.log)

**Comment by uroskrkic** [comment]
Hello,

In meantime, I had to find a quick fix for the issue mentioned. I did it in a separate fork.
However, this is the fix which has to be done.

Target file: **module.modulemap**

<img width="565" alt="Screen Shot 2019-05-17 at 15 12 20" src="https://user-images.githubusercontent.com/23169907/57930451-4cd63b00-78b6-11e9-8d30-82cbb9800263.png">

**Comment by ashwinp-r** [comment]
^ Did you ever figure out how to resolve this?
